### ISSUE TITLE
ElasticSearch Sink Implementation

### ISSUE THREAD

**Issue by ardy564** [PoShLog/PoShLog#14]
Anyone working on this?

**Comment by TomasBouda** [comment]
Hi, I'm not sure, but I think the answer is no :)
But you have some options: 
- Implement it on your own 🚀 Here is PoShLog sink template repository - [PoShLog.Sinks.Template](https://github.com/PoShLog/PoShLog.Sinks.Template) and here is serilog sink you need to wrap - [serilog-sinks-elasticsearch](https://github.com/serilog/serilog-sinks-elasticsearch). I still didn't push myself to create some nice tutorial, but feel free to ask any questions on discord.
- Or I can prepare it for you, but it's gonna take some time until I get to it :)

Let me know what's it gonna be 👍

**Comment by mamidenn** [comment]
I am currently looking into this.

**Comment by mamidenn** [comment]
I have implemented a working [serilog-sinks-elasticsearch](https://github.com/serilog/serilog-sinks-elasticsearch) wrapper here: [PoShLog.Sinks.Elasticsearch](https://github.com/mamidenn/PoShLog.Sinks.Elasticsearch).

Only a small portion of `ElasticsearchSinkOptions` is wrapped as of now. Feel free to open an issue over there if there is a perticular option that you would need that is not yet implemented.

@ardy564 : If you are still interested in an Elasticsearch PoShLog sink, I would be happy if you could give it a spin and report any issues to me.

**Comment by TomasBouda** [comment]
hi Martin, great job! 👍 and thanks for helping to improve PoShlog 🙏 I'm sure many users will appreciate it.
I've updated wiki and added links to your project, if you have some spare time you can create wiki page in your repo
describing your sink(*like [this](https://github.com/PoShLog/PoShLog/wiki/Add-SinkFile) for example*) and I'll update those links again.

Thanks again and happy coding 🚀
