### ISSUE TITLE
Dotaz: Logovaci soubor

### ISSUE THREAD

**Issue by walliscz** [PoShLog/PoShLog#17]
Ahoj, jak zjistím do jakého souboru aktuálně zapisuje?

`
$LogPath = "c:\tmp\"
New-Logger -verbose | 
            Set-MinimumLevel -Value Verbose | 
            Add-SinkFile -Path "$($LogPath)test-.log" -RollingInterval Day -OutputTemplate '{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}' | 
            #Add-SinkConsole | 
            Start-Logger `

neco jako:
`(Get-Logger).sinkfile.filepath > c:\tmp\test-20201230.log`

**Comment by TomasBouda** [comment]
Ahoj,

bohužel v PoShLogu(*ani v Serilogu*, [viz](https://github.com/serilog/serilog-sinks-file/issues/129)) to zatím jednoduše nejde. Každopádně by bylo fajn mít na to nějakoý cmdlet/property, zkusím se zamyslet, jak to nejlépe udělat a přidat to v dalším releasu.

Nejjednodušší řešení je asi najít poslední upravený soubor ve složce do které se loguje, ve tvém příkladu tedy `$LogPath`.

```ps1
$LogPath = "c:\tmp\"

New-Logger -verbose | 
	Set-MinimumLevel -Value Verbose | 
	Add-SinkFile -Path "$($LogPath)test-.log" -RollingInterval Day -OutputTemplate '{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}' | 
	Add-SinkConsole | 
	Start-Logger

Write-InfoLog 'Ahoj'

$logFilePath = Get-ChildItem $LogPath -Filter '*.log' | Sort-Object { $_.LastWriteTime } | Select-Object -Last 1

Write-InfoLog 'Affected log file: {logFile}' -PropertyValues $logFilePath

Close-Logger
```
```
[12:37:08 INF] Ahoj
[12:37:08 INF] Affected log file: C:\tmp\test-20201230.log
```

Snad to alespoň trochu pomůže a díky za feedback 👍

**Comment by TomasBouda** [comment]
Hi, it'll be posible to get current log file/files using `Get-CurrentLogFiles` cmdlet in PoShLog version 2.2.0 so stay tuned if you're intrested 👍
