### ISSUE TITLE
Write-*Log CmdLets do not support pipeline input

### ISSUE THREAD

**Issue by mamidenn** [PoShLog/PoShLog#19]
I would like to be able to pipe the output of CmdLets or called programs into `Write-*Log`. Currently, only the last element of the input gets actually logged.

```ps1
New-Logger | Add-SinkConsole | Start-Logger
'Foo', 'Bar', 'Baz' | Write-InfoLog
Close-Logger
```

Expected:
```
[13:37:00 INF] Foo
[13:37:00 INF] Bar
[13:37:00 INF] Baz

# Or

[13:37:00 INF] Foo
Bar
Baz
```

Actual:
```
[13:37:00 INF] Baz
``` 

This is due to the CmdLets using `ValueFromPipeline` for the `$MessageTemplate` parameter but not wrapping the execution body in a `Process` block. Basically, all that needs to be done is replace this
```ps1
Write-Log -MessageTemplate $MessageTemplate -Logger $Logger -Exception $Exception -ErrorRecord $ErrorRecord -PropertyValues $PropertyValues -PassThru:$PassThru
```
with this in all the CmdLets:
```ps1
Process {
    Write-Log -MessageTemplate $MessageTemplate -Logger $Logger -Exception $Exception -ErrorRecord $ErrorRecord -PropertyValues $PropertyValues -PassThru:$PassThru
}
```

I can open a PR if you are interested in this.
Also big props for this nice project 👍.

**Comment by TomasBouda** [comment]
hi again Martin, you rock 👍 thanks for fixing this
saw your PR, I'll fix the pipeline(*yes, it fails because of unrelated issue*) and then I'll merge it in.

I have some unfinished changes in PoShLog, so I will release your fix when I'm done.
