### ISSUE TITLE
Suggest adding sink for Windows event log

### ISSUE THREAD

**Issue by e2ibrobbins** [PoShLog/PoShLog#2]
What would it take to add an event log sink?

**Comment by TomasBouda** [comment]
Hi, 
thanks for asking. That should be quite easy 😊 I just need to write wrapper module for this [library](https://github.com/serilog/serilog-sinks-eventlog). I'm currently working on adding more sinks(seq, email) so I will add windows event log on my list 👍 
I think by the end of next week it should be all done. I will keep you updated.

**Comment by TomasBouda** [comment]
Hi,
finally got to that 😏 Here is prepared repo https://github.com/PoShLog/PoShLog.Sinks.EventLog
I'll release it tomorow.

**Comment by TomasBouda** [comment]
Ok, released it as preview, for now. Use is like this:

```ps1
Install-Module -Name PoShLog.Sinks.EventLog -AllowPrerelease
```

**On first use you must run the script as Administrator and you need to add `-ManageEventSource $true` parameter to register `-Source`(Sample Script in example bellow).** Then you can run the script normaly and you can ommit `-ManageEventSource` parameter.

```ps1
Import-Module PoShLog
Import-Module PoShLog.Sinks.EventLog

New-Logger |
	Add-SinkEventLog -Source 'Sample Script' -ManageEventSource $true |
	Add-SinkConsole |
	Start-Logger

Write-InformationLog 'Test message in windows event log'

Close-Logger
```

![image](https://user-images.githubusercontent.com/7009780/85843663-c4f17e80-b7a1-11ea-9207-0ce3eed031a3.png)

**Comment by TomasBouda** [comment]
I'm gonna close this issue as I already published [PoShLog.Sinks.EventLog](https://www.powershellgallery.com/packages/PoShLog.Sinks.EventLog/1.0.0) and there is no feedback from @e2ibrobbins.

**Comment by drullo** [comment]
> Hi,
> thanks for asking. That should be quite easy 😊 I just need to write wrapper module for this [library](https://github.com/serilog/serilog-sinks-eventlog). I'm currently working on adding more sinks(seq, email) so I will add windows event log on my list 👍
> I think by the end of next week it should be all done. I will keep you updated.

Would love to see Seq.  That's the most important one for my team.

**Comment by TomasBouda** [comment]
Hi,

it already exist - [PoShLog.Sinks.Seq](https://github.com/PoShLog/PoShLog.Sinks.Seq) 😃 I just forget to put it in documentation. Feel free to post any feedback in [discussions](https://github.com/PoShLog/PoShLog/discussions), [discord ](https://discord.gg/gGFtbf) or create new issue.
