### ISSUE TITLE
Support for Azure Application Insights Sink

### ISSUE THREAD

**Issue by cravecode** [PoShLog/PoShLog#23]
Your PS module looks awesome. Thank BTW!
I'd like to use [Azure Application Insights Sink](https://github.com/serilog/serilog-sinks-applicationinsights). I was looking over your Http Sink as an example of how I'd attempt to contribute a PR supporting this sink. Is the build/packaging process as simple simple as calling your `build.ps1`? Any thoughts on where I may run into issues? Thanks!!

**Comment by TomasBouda** [comment]
Hi,
thanks for helping to improve PoShLog 👍 I've prepared wiki page on how to create sink - [https://github.com/PoShLog/PoShLog/wiki/Creating-Sink](https://github.com/PoShLog/PoShLog/wiki/Creating-Sink)
I'll keep updating it, if you have any question or feedback, feel free to reply here or in [discussion here](https://github.com/PoShLog/PoShLog/discussions/22).
Good luck 👍
