### ISSUE TITLE
Console sink cannot handle debug and verbose messages in PowerShell

### ISSUE THREAD

**Issue by gitbute** [PoShLog/PoShLog#4]
Hi 

Found another bug in console sink.
Write-VerboseLog as well as Write-DebugLog never outputs to console.
I tried with $VerbosePreference 'Continue' as well as with a function call -Verbose.

Best regards

Edit:
A possible solution could be:
In Write-VerboseLog, check if console sink is active and if it is, output the Message to Write-Verbose.

**Comment by TomasBouda** [comment]
Hi,
did you set minimum log level to verbose/debug? By default minimum log level is set to `Information`, which means that, all log levels beneath `Information` will be ommited.
You can use [Set-MinimumLevel](https://github.com/PoShLog/PoShLog/wiki/Set-MinimumLevel) to set lower minimum log level.

In examples bellow you can see two ways how to create logger that will log [all log levels](https://github.com/PoShLog/PoShLog/wiki/Log-event-levels), including `Verbose` and `Debug`.

```ps1
# Short version
Start-Logger -FilePath 'C:\Logs\test.log' -Console -MinimumLevel Verbose

########################################
# Or use full fluent api

New-Logger | # Create new instance of logger configuration
    Set-MinimumLevel -Value Verbose | # Set minimum level, below which no events should be generated
    Add-SinkFile -Path 'C:\Logs\test.log'  | # Add sink that will write our event messages into file
    Add-SinkConsole | # Add sink that will log our event messages into console host
    Start-Logger # Start logging
```

Hope this is helpful. If you are still having problems, don't hesitate to contact me ✋

**Comment by TomasBouda** [comment]
I've eddited [Readme.md](https://github.com/PoShLog/PoShLog/blob/master/README.md), I can see, that the example was bit misleading, as it was missing `Set-MinimumLevel` cmdlet 😏

**Comment by gitbute** [comment]
Thanks for pointing me to Set-MinimumLevel, i got it to work now!
One problem is still that it does not comply with streams, but i did another issue for that.
For Example:
No matter if you put -Verbose or not, verbose messages get displayed.
