### ISSUE TITLE
Set ValueFromPipelineByPropertyName=$True for parameters

### ISSUE THREAD

**Issue by kvanh** [PoShLog/PoShLog#6]
I like using splats for setting parameters on functions, the code is cleaner and easier to comment and read. Setting ValueFromPipelineByPropertyName=$True for parameters allows spats to be used. I tested this by modifying my installation of PoSHLog but it changes so many files I didn't think a pull request was appropriate.

Here's your sample code i modified to use splats:
```powershell
$ScriptName = 'TestLogging'

# FileSink Settings
$fileSink = @{
	# Log to user's AppData\Local directory
	Path = "$($ENV:LocalAppData)\$($ScriptName)-.log"
	RollingInterval = 'Day' # Infinite | Year | Month | Day | Hour | Minute
	# Roll on file size AND day
	RollOnFileSizeLimit = $true
	RetainedFileCountLimit = 5
}

New-Logger |
    Set-MinimumLevel -Value Verbose |
    Add-SinkFile @fileSink |
    Add-SinkConsole |
    Start-Logger

# Test all log levels
Write-VerboseLog 'Test verbose message'
Write-DebugLog 'Test debug message'
Write-InfoLog 'Test info message'
Write-WarningLog 'Test warning message'
Write-ErrorLog 'Test error message'
Write-FatalLog 'Test fatal message'

# Example of formatted output
$position = @{
    Latitude = 25
    Longitude = 134
}
$elapsedMs = 34

Write-InfoLog 'Processed {@Position} in {Elapsed:000} ms.' -PropertyValues $position, $elapsedMs

Close-Logger
```

**Comment by TomasBouda** [comment]
Hi,

I'm not sure where is the problem 😕 I tryed your code in PS 5.1 and 7.0.2 and it worked fine without me changing anything in module. Where exactly did you need `ValueFromPipelineByPropertyName` parameter?

**Comment by kvanh** [comment]
Gah. I just uninstalled the module with my changes, reinstalled the 2.0.0 version from the Gallery and it works fine with splatting. I have no idea what error i ran into now.  Closing this.

Unnecessary additional info:
This was on Windows Server 2016 Standard with PowerShell 5.1

**Comment by TomasBouda** [comment]
Alright, thanks for the feedback 👍
